### ISSUE TITLE
App Hang

### ISSUE THREAD

**Issue by cxbignekoc** [alex-kabin/abr-viewer#1]
Hi

App Hang on Machine

**Win 10 Pro
i7 4790
Radeon R 390

Brushes in separate Folder, used for Affinity Photo
**

#1 The Program suddenly closed by Browsing Brushes in Brushes Folder.

#2 Sometimes with Popup Error without closing the app after accept with OK

Message
```
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.

   bei AK.Abr.AbrReader.CreateImage(Int32 width, Int32 height, Byte[] buffer, CancellationToken cancellationToken) in D:\Projects\my\abr-viewer\AK.Abr\AbrReader.cs:Zeile 77.

   bei AK.Abr.AbrReader.ReadVer12(EndianBinaryReader ebr, Int32 ver, CancellationToken cancellationToken) in D:\Projects\my\abr-viewer\AK.Abr\AbrReader.cs:Zeile 146.

   bei AK.Abr.AbrReader.ReadCore(CancellationToken cancellationToken) in D:\Projects\my\abr-viewer\AK.Abr\AbrReader.cs:Zeile 33.

   bei AK.Abr.AbrReader.<>c__DisplayClass9_0.<ReadAsync>b__0() in D:\Projects\my\abr-viewer\AK.Abr\AbrReader.cs:Zeile 230.

   bei System.Threading.Tasks.Task.InnerInvoke()

   bei System.Threading.Tasks.Task.Execute()
```

#1 
Started just from the unzipped Download Folder.
I just was adjusting the Thumb Size then Browsing some *.abr in the abr-viewer.
Someold .abr

The same happens if i delete the .abr in the Win File Explorer and choose this .abr again in the abr-Viewer.

process:

- watching a brush in the viewer 
- click the next .abr container
- go to Explorer in second window 
- delete the previous .abr 
- the abr is still there in the abr-viewer yet
- if i click on the deleted one, the app closed without pop-up warning

Report.txt is available, just write me if you needmore
Cheers*

#1 
```
Win Error:
Fehlerbucket 2207606046717621328, Typ 5
Ereignisname: CLR20r3
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: AbrViewer.exe
P2: 1.0.0.0
P3: 5e4bcb82
P4: AK.Abr
P5: 1.0.0.0
P6: 5e4bcb81
P7: 1e
P8: 20
P9: System.IO.FileNotFoundException
P10: 

```

**Comment by alex-kabin** [comment]
@cxbignekoc, thanks for reporting bug! 
Fixed in v1.1: added folder watcher to track external changes, also added in-app file delete function.
