### ISSUE TITLE
There is no .exe file

### ISSUE THREAD

**Issue by cy2201** [alex-kabin/abr-viewer#2]
Hi,

I want to use your software. In your readme you write start the exe file but there is no exe file in your repository. Do I have to compile this software by myself? I don't know how.

Thank you.

**Comment by alex-kabin** [comment]
Hello!
Please, download latest release (https://github.com/alex-kabin/abr-viewer/releases/download/1.1/AbrViewer-1.1.zip), **unzip** archive, then run AbrViewer.exe.
Thanks for using my software)
