### ISSUE TITLE
A positive from Virus total?  

### ISSUE THREAD

**Issue by ak33tah** [alex-kabin/abr-viewer#4]
Hey I'm getting a virus total warning from the zip file do you know what's going on?

https://www.virustotal.com/gui/file/6c400ebdc9ff317ee16a0d6a205a2c7b014ce7a29f13e65b8e45c0287ecbc264?nocache=1

**Comment by alex-kabin** [comment]
Hi! It is definitely a mistake of a single antivirus. Zip file is absolutely virus-free (it was build 4 year ago and no problems since then). But if you in doubt - you can always compile application from sources by yourself)
Nevertheless I will rebuild project later to avoid such confusion.

**Comment by ak33tah** [comment]
Thanks for the reply.  It was just a small OCD of mine.  But the program itself, I mean 4 years later, and it still works fine!
